= Docker Image for Antora 
:uri-antora: https://antora.org
:uri-asciidoctor: https://asciidoctor.org
:uri-license: https://www.mozilla.org/en-US/MPL/2.0/

This repository hosts the official Docker image for Antora.

== What is Antora?

{uri-antora}[Antora] is a modular static site generator designed for creating documentation sites from AsciiDoc documents.
Its site generator pipeline aggregates documents from versioned content repositories and processes them using {uri-asciidoctor}[Asciidoctor].

[#use-image]
== How to Use this Image

This image is published to Docker Hub.
The name of the image is `antora/antora`.
The purpose of the image is to execute the `antora` command.

If you want to help improve this image, you should learn how to <<build-image,build and install it locally>>.

[#run-image]
=== Run the Image Directly

This image is intended to be used as a command in a box.
You can use this image as a replacement for the `antora` command to execute a playbook.
The benefit is that you don't actually to install Antora itself.

To demonstrate how to use this image, we'll be using the https://gitlab.com/antora/demo/demo-site[Antora demo site].
Start by cloning the playbook repository for the demo site, then switch to the newly created folder:

 $ git clone https://gitlab.com/antora/demo/demo-site.git
   cd demo-site

Next, run the `docker run` command to run this image directly, which implicitly runs the `antora` command inside the container:

 $ docker run -v `pwd`:/antora --rm -t antora/antora --stacktrace site.yml

The `-t` flag allocates a pseudo-TTY, which is required if you want to see the progress bars for git operations.

If you're running a Linux distribution like Fedora that has SELinux enabled, you'll need to add the `--privileged` flag in order to use the volume mount.
You'll also want to add the `-u $UID` option to instruct Docker to run the entrypoint command as the current user (otherwise, files will be written as root and thus hard to delete).

 $ docker run -u $UID --privileged -v `pwd`:/antora --rm -t antora/antora --stacktrace site.yml

If you want to shell into the container, set the `--entrypoint` option as follows:

 $ docker run --entrypoint ash --privileged -v `pwd`:/antora --rm -it antora/antora

This command allows you to use the `antora` command inside the running container (but still generate files to the local filesystem).

[#extend-image]
=== Use as a Base Image

You can use this image as a base for your own image.

. Create a custom Dockerfile file named [.path]_Dockerfile.custom_
. Populate that file with the following contents:
+
.Dockerfile.custom
[source,docker]
----
FROM antora/antora

RUN yarn global add asciidoctor-plantuml <1>
----
<1> Adds a custom extension to the base image.

. Build the image using the following command:

 $ docker build -t local/antora:custom -f Dockerfile.custom .

Once the build is finished, you can use the image name `local/antora:custom` to run the container.

To see a list of your images, run the following command:

 $ docker images

[#ci-image]
=== Run in gitlab-ci

Since the default entry point of the image is the command `antora` itself, you will have to define another entry point to use it as your base image in your `gitlab-ci.yml` file as this :

[source,yaml]
----
image: 
  name: antora/antora:1.0.0
  entrypoint: [/bin/sh, -c]
----

If you don't do so, you will obtain this error message :

[source,bash]
----
error: unknown option `-c'
----

just after the `Skipping Git submodules setup` line.

After this change, you will be able to use the command `antora` inside your gitlab CI :

[source,yaml] 
----
  script:
  - antora site.yml
----

[#build-image]
== How to Build this Image

To build this image locally, use the following command:

 $ docker build -t local/antora .

The build make take awhile to complete.
Once it's finished, you can use the image name `local/antora` (i.e., `local/antora:latest`) to run the container.

== Copyright and License

Copyright (C) 2018 OpenDevise Inc. and the Antora Project.

Use of this software is granted under the terms of the {uri-license}[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.
